name: PR Checks and Auto-Merge

on:
  pull_request:
    branches:
      - main

# permissions:
#   contents: write
#   pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Branch Details
        run: |
          echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here
          echo "Tests passed!"

  merge-pr:
    needs: run-tests
    if: contains(github.event.pull_request.head.ref, 'update')
    runs-on: ubuntu-latest
    steps:
      - name: Automerge PR
        uses: peter-evans/merge@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          merge_method: squash
